let contenItems = [
    {
        "style": 1,
        "kind": "discover",
        "id": "m1",
        "title": "ahermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1152/12857/Signature-TShirt-Grey-02-R-Web__64055.1616106150.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 121,
    },
    {
        "style": 1,
        "kind": "discover",
        "id": "m2",
        "title": "bhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1144/12807/Fleece-Hoodie-Black-03-R-Web__97361.1616432335.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 83,
    },
    {
        "style": 1,
        "kind": "discover",
        "id": "m3",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1152/12857/Signature-TShirt-Grey-02-R-Web__64055.1616106150.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 93,
    },
    {
        "style": 1,
        "kind": "discover",
        "id": "m4",
        "title": "khermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1142/12751/Block-stringer-sage-18-R__33906.1614034535.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 76,
    },
    {
        "style": 1,
        "kind": "discover",
        "id": "m5",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1152/12857/Signature-TShirt-Grey-02-R-Web__64055.1616106150.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 85,
    },
    {
        "style": 1,
        "kind": "discover",
        "id": "m6",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/841/9183/AvidLongSleeve-Red2-R-Web__05227.1603403030.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 95,
    },
    {
        "style": 1,
        "kind": "discover",
        "id": "m7",
        "title": "ehermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1144/12807/Fleece-Hoodie-Black-03-R-Web__97361.1616432335.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 66,
    },
    {
        "style": 1,
        "kind": "women",
        "id": 7,
        "title": "ehermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 66,
    },
    {
        "style": 1,
        "kind": "women",
        "id": 8,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/909/9816/Block-TShirt-Black-01-R__77977.1574541118.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 150,
    },
    {
        "style": 1,
        "kind": "women",
        "id": 9,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 64,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 10,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/909/9816/Block-TShirt-Black-01-R__77977.1574541118.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 53,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 11,
        "title": "fhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 79,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 12,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 63,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 13,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/909/9816/Block-TShirt-Black-01-R__77977.1574541118.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 84,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 14,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 63,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 15,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/909/9816/Block-TShirt-Black-01-R__77977.1574541118.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 73,
    },
    {
        "style": 1,
        "kind": "women",
        "id": 16,
        "title": "dhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 76,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 17,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/909/9816/Block-TShirt-Black-01-R__77977.1574541118.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 77,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 18,
        "title": "mhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 73,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 19,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 63,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 20,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 99,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 21,
        "title": "zhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/909/9816/Block-TShirt-Black-01-R__77977.1574541118.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 63,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 22,
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 95,
    },
    {
        "style": 2,
        "kind": "women",
        "id": 23,
        "title": "mhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1089/12252/Ribbon-Tank-Sand01-R-Web__74353.1605658812.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 63,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc1",
        "title": "ahermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1009/12233/Wrist-wraps-black04__52511.1604694391.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 121,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc2",
        "title": "bhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/998/11323/ResistanceBand-Medium-Pink-01_2-Web__44121.1596464298.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 83,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc3",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/916/9955/Protein-Shaker-WhiteRed-01__62930.1574791822.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 93,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc4",
        "title": "khermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/999/11315/ResistanceBand-Light-LightGrey-01_2-Web__90574.1596464277.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 76,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc5",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1006/11080/Speed-rope-black-01__30032.1594147987.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 85,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc6",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1001/11334/Yoga-Mat-01_2-Web__65223.1596464906.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 95,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc7",
        "title": "ehermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1007/11071/Speed-rope-red-01__63818.1594147878.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 66,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc8",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1008/12230/Lifting-straps-black01__31191.1604685131.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 150,
    },
    {
        "style": 1,
        "kind": "accessories",
        "id": "acc9",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/998/11323/ResistanceBand-Medium-Pink-01_2-Web__44121.1596464298.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 64,
    },
    {
        "style": 2,
        "kind": "accessories",
        "id": "acc10",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1009/12233/Wrist-wraps-black04__52511.1604694391.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 53,
    },
    {
        "style": 2,
        "kind": "accessories",
        "id": "acc11",
        "title": "fhermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/998/11323/ResistanceBand-Medium-Pink-01_2-Web__44121.1596464298.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 79,
    },
    {
        "style": 2,
        "kind": "accessories",
        "id": "acc12",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1010/11062/Resistance-tubes-01__51359.1604677089.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 63,
    },
    {
        "style": 2,
        "kind": "accessories",
        "id": "acc13",
        "title": "ThermaTec Hoodie",
        "img": "https://cdn11.bigcommerce.com/s-iyqvgyco/images/stencil/450x630/products/1009/12233/Wrist-wraps-black04__52511.1604694391.jpg?c=2",
        "descreption": "COMFORTABLE & VERSATILE. Featuring a modern tapered fit made using a soft blend of cotton and elastane, the Agile Bottoms have been carefully crafted with freedom of movement in mind. Super stretchy with an adjustable draw cord to provide maximum...",
        "price": 84,
    },

]

